from __future__ import annotations

from paperlens_core.report.graph_export import render_core_graph_report_view
from paperlens_core.report.graph_view import (
    GraphReportDraft,
    ReportParagraph,
    ReportSection,
    audit_report_draft_against_graph,
    build_report_draft_from_graph,
    render_graph_report_markdown,
)
from paperlens_core.report.overview import (
    core_graph_report_link,
    display_paper_title,
    display_row_title,
    humanize_display_title,
    is_internal_review_noise,
    markdown_title,
    one_line_row_reason,
    render_paperlens_report,
    user_visible_review_items,
)
from paperlens_core.report.rows import (
    classification_counts,
    cluster_rows_by_scope,
    describe_rows,
    higher_read_effort_label,
    novelty_risk,
    paper_report_filename,
    read_decision,
    read_effort_rank,
    reading_priority_key,
    report_link_lines,
    row_decision,
    row_relation,
)
from paperlens_core.report.text import (
    clean_model_inline_text,
    clean_model_markdown,
    compact_compare_text,
    compact_reason,
    compact_string_list,
    readable_model_body,
    recommendation_for_grade,
    sanitize_reader_hostile_text,
    user_facing_uncertainty_note,
)

__all__ = [
    "GraphReportDraft",
    "ReportParagraph",
    "ReportSection",
    "audit_report_draft_against_graph",
    "build_report_draft_from_graph",
    "classification_counts",
    "clean_model_inline_text",
    "clean_model_markdown",
    "cluster_rows_by_scope",
    "compact_compare_text",
    "compact_reason",
    "compact_string_list",
    "core_graph_report_link",
    "describe_rows",
    "display_paper_title",
    "display_row_title",
    "higher_read_effort_label",
    "humanize_display_title",
    "is_internal_review_noise",
    "markdown_title",
    "novelty_risk",
    "one_line_row_reason",
    "paper_report_filename",
    "read_decision",
    "read_effort_rank",
    "readable_model_body",
    "reading_priority_key",
    "recommendation_for_grade",
    "render_core_graph_report_view",
    "render_graph_report_markdown",
    "render_paperlens_report",
    "report_link_lines",
    "row_decision",
    "row_relation",
    "sanitize_reader_hostile_text",
    "user_facing_uncertainty_note",
    "user_visible_review_items",
]
